openapi: 3.1.0
info:
  title: API backend service
  version: "1.0"
servers:
  - url: /api

paths:
  /hello:
    get:
      tags:
        - api
      description: Hello
      security:
        - bearerAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      summary: Hello
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: "Hello, World!"
