openapi: 3.1.0
info:
  title: API backend service
  version: "1.0"
servers:
  - url: /
paths:
  /get_user_role:
    get:
      tags:
        - hello
      description: Hello
      security:
        - bearerAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      summary: Hello
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                message: "Hello, World!"
